name: Changelog Monitor

on:
  schedule:
    # - cron: '*/5 * * * *'  # Runs every 5 minutes
    - cron: "0 */1 * * *" # Run every hour
    # - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    # - cron: '0 9 * * *'  # Runs at 10:00 CET (during standard time)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run monitor
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: npm run scrap
